package tomweb.xyz.bjcms.pojo;

import java.util.Date;

public class AdminInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.admin_id
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.account
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.password
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.nick_name
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.status
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.lock_time
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    private Date lockTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_info.login_ip
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    private String loginIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.admin_id
     *
     * @return the value of admin_info.admin_id
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.admin_id
     *
     * @param adminId the value for admin_info.admin_id
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.account
     *
     * @return the value of admin_info.account
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.account
     *
     * @param account the value for admin_info.account
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.password
     *
     * @return the value of admin_info.password
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.password
     *
     * @param password the value for admin_info.password
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.nick_name
     *
     * @return the value of admin_info.nick_name
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.nick_name
     *
     * @param nickName the value for admin_info.nick_name
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.status
     *
     * @return the value of admin_info.status
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.status
     *
     * @param status the value for admin_info.status
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.lock_time
     *
     * @return the value of admin_info.lock_time
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public Date getLockTime() {
        return lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.lock_time
     *
     * @param lockTime the value for admin_info.lock_time
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_info.login_ip
     *
     * @return the value of admin_info.login_ip
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_info.login_ip
     *
     * @param loginIp the value for admin_info.login_ip
     *
     * @mbg.generated Sun Jul 12 23:06:17 CST 2020
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }
}