package tomweb.xyz.bjcms.pojo;

import java.util.ArrayList;
import java.util.List;

public class BjAccountExample {
    /**
     * bj_account
     */
    protected String orderByClause;

    /**
     * bj_account
     */
    protected boolean distinct;

    /**
     * bj_account
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public BjAccountExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_account
     *
     * @mbg.generated 2020-07-08
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * bj_account 2020-07-08
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppTokenIsNull() {
            addCriterion("app_token is null");
            return (Criteria) this;
        }

        public Criteria andAppTokenIsNotNull() {
            addCriterion("app_token is not null");
            return (Criteria) this;
        }

        public Criteria andAppTokenEqualTo(String value) {
            addCriterion("app_token =", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotEqualTo(String value) {
            addCriterion("app_token <>", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenGreaterThan(String value) {
            addCriterion("app_token >", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenGreaterThanOrEqualTo(String value) {
            addCriterion("app_token >=", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenLessThan(String value) {
            addCriterion("app_token <", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenLessThanOrEqualTo(String value) {
            addCriterion("app_token <=", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenLike(String value) {
            addCriterion("app_token like", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotLike(String value) {
            addCriterion("app_token not like", value, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenIn(List<String> values) {
            addCriterion("app_token in", values, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotIn(List<String> values) {
            addCriterion("app_token not in", values, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenBetween(String value1, String value2) {
            addCriterion("app_token between", value1, value2, "appToken");
            return (Criteria) this;
        }

        public Criteria andAppTokenNotBetween(String value1, String value2) {
            addCriterion("app_token not between", value1, value2, "appToken");
            return (Criteria) this;
        }

        public Criteria andServerUrlIsNull() {
            addCriterion("server_url is null");
            return (Criteria) this;
        }

        public Criteria andServerUrlIsNotNull() {
            addCriterion("server_url is not null");
            return (Criteria) this;
        }

        public Criteria andServerUrlEqualTo(String value) {
            addCriterion("server_url =", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotEqualTo(String value) {
            addCriterion("server_url <>", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlGreaterThan(String value) {
            addCriterion("server_url >", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlGreaterThanOrEqualTo(String value) {
            addCriterion("server_url >=", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlLessThan(String value) {
            addCriterion("server_url <", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlLessThanOrEqualTo(String value) {
            addCriterion("server_url <=", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlLike(String value) {
            addCriterion("server_url like", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotLike(String value) {
            addCriterion("server_url not like", value, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlIn(List<String> values) {
            addCriterion("server_url in", values, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotIn(List<String> values) {
            addCriterion("server_url not in", values, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlBetween(String value1, String value2) {
            addCriterion("server_url between", value1, value2, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerUrlNotBetween(String value1, String value2) {
            addCriterion("server_url not between", value1, value2, "serverUrl");
            return (Criteria) this;
        }

        public Criteria andServerTokenIsNull() {
            addCriterion("server_token is null");
            return (Criteria) this;
        }

        public Criteria andServerTokenIsNotNull() {
            addCriterion("server_token is not null");
            return (Criteria) this;
        }

        public Criteria andServerTokenEqualTo(String value) {
            addCriterion("server_token =", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenNotEqualTo(String value) {
            addCriterion("server_token <>", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenGreaterThan(String value) {
            addCriterion("server_token >", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenGreaterThanOrEqualTo(String value) {
            addCriterion("server_token >=", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenLessThan(String value) {
            addCriterion("server_token <", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenLessThanOrEqualTo(String value) {
            addCriterion("server_token <=", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenLike(String value) {
            addCriterion("server_token like", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenNotLike(String value) {
            addCriterion("server_token not like", value, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenIn(List<String> values) {
            addCriterion("server_token in", values, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenNotIn(List<String> values) {
            addCriterion("server_token not in", values, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenBetween(String value1, String value2) {
            addCriterion("server_token between", value1, value2, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerTokenNotBetween(String value1, String value2) {
            addCriterion("server_token not between", value1, value2, "serverToken");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyIsNull() {
            addCriterion("server_encoding_a_e_s_key is null");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyIsNotNull() {
            addCriterion("server_encoding_a_e_s_key is not null");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyEqualTo(String value) {
            addCriterion("server_encoding_a_e_s_key =", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyNotEqualTo(String value) {
            addCriterion("server_encoding_a_e_s_key <>", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyGreaterThan(String value) {
            addCriterion("server_encoding_a_e_s_key >", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyGreaterThanOrEqualTo(String value) {
            addCriterion("server_encoding_a_e_s_key >=", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyLessThan(String value) {
            addCriterion("server_encoding_a_e_s_key <", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyLessThanOrEqualTo(String value) {
            addCriterion("server_encoding_a_e_s_key <=", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyLike(String value) {
            addCriterion("server_encoding_a_e_s_key like", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyNotLike(String value) {
            addCriterion("server_encoding_a_e_s_key not like", value, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyIn(List<String> values) {
            addCriterion("server_encoding_a_e_s_key in", values, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyNotIn(List<String> values) {
            addCriterion("server_encoding_a_e_s_key not in", values, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyBetween(String value1, String value2) {
            addCriterion("server_encoding_a_e_s_key between", value1, value2, "serverEncodingAESKey");
            return (Criteria) this;
        }

        public Criteria andServerEncodingAESKeyNotBetween(String value1, String value2) {
            addCriterion("server_encoding_a_e_s_key not between", value1, value2, "serverEncodingAESKey");
            return (Criteria) this;
        }
    }

    /**
     * bj_account
     */
    
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * bj_account 2020-07-08
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}