package tomweb.xyz.bjcms.pojo;

public class CarticleOverPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carticle_over_photo.article_id
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carticle_over_photo.photo_url
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    private String photoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carticle_over_photo.order_no
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    private Integer orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carticle_over_photo.article_id
     *
     * @return the value of carticle_over_photo.article_id
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carticle_over_photo.article_id
     *
     * @param articleId the value for carticle_over_photo.article_id
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carticle_over_photo.photo_url
     *
     * @return the value of carticle_over_photo.photo_url
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carticle_over_photo.photo_url
     *
     * @param photoUrl the value for carticle_over_photo.photo_url
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl == null ? null : photoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carticle_over_photo.order_no
     *
     * @return the value of carticle_over_photo.order_no
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carticle_over_photo.order_no
     *
     * @param orderNo the value for carticle_over_photo.order_no
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }
}