package tomweb.xyz.bjcms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tomweb.xyz.bjcms.pojo.AdminInfo;
import tomweb.xyz.bjcms.pojo.AdminInfoExample;

public interface AdminInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    long countByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int deleteByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int insert(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int insertSelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    List<AdminInfo> selectByExample(AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    AdminInfo selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int updateByExample(@Param("record") AdminInfo record, @Param("example") AdminInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int updateByPrimaryKeySelective(AdminInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_info
     *
     * @mbg.generated Sun Jul 12 22:19:13 CST 2020
     */
    int updateByPrimaryKey(AdminInfo record);
}