package tomweb.xyz.bjcms.dao;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import tomweb.xyz.bjcms.pojo.BjArticle;
import tomweb.xyz.bjcms.pojo.BjArticleExample;

import java.util.List;

/**
* Created by Mybatis Generator on 2020/07/10
*/
@Repository
@Mapper
public interface BjArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    long countByExample(BjArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int deleteByExample(BjArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int insert(BjArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int insertSelective(BjArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    List<BjArticle> selectByExampleWithBLOBs(BjArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    List<BjArticle> selectByExample(BjArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    BjArticle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int updateByExampleSelective(@Param("record") BjArticle record, @Param("example") BjArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int updateByExampleWithBLOBs(@Param("record") BjArticle record, @Param("example") BjArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int updateByExample(@Param("record") BjArticle record, @Param("example") BjArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int updateByPrimaryKeySelective(BjArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int updateByPrimaryKeyWithBLOBs(BjArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bj_article
     *
     * @mbg.generated 2020-07-10
     */
    int updateByPrimaryKey(BjArticle record);
}