package tomweb.xyz.bjcms.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import tomweb.xyz.bjcms.pojo.CarticleOverPhoto;
import tomweb.xyz.bjcms.pojo.CarticleOverPhotoExample;

public interface CarticleOverPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carticle_over_photo
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    long countByExample(CarticleOverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carticle_over_photo
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    int deleteByExample(CarticleOverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carticle_over_photo
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    int insert(CarticleOverPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carticle_over_photo
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    int insertSelective(CarticleOverPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carticle_over_photo
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    List<CarticleOverPhoto> selectByExample(CarticleOverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carticle_over_photo
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") CarticleOverPhoto record, @Param("example") CarticleOverPhotoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carticle_over_photo
     *
     * @mbg.generated Fri Jul 10 23:16:35 CST 2020
     */
    int updateByExample(@Param("record") CarticleOverPhoto record, @Param("example") CarticleOverPhotoExample example);
}